LOGFORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(filename)s:%(lineno)d'
LOGFILE = "app.log"
DEBUG = True
APP_PORT = 1712
NET_DATA = "172.6.0.1/255.255.255.0"  ##<GATEWAY_IP>/<NET_MASK>
MAX_NODE_COUNT = 4
DEFAULT_ENCODING = "utf-8"
BROADCAST_WAIT_TIMEOUT = 4.0
MAX_PACKET_SIZE = 4096
